### ISSUE TITLE
Resource group template

### ISSUE THREAD

**Issue by jagsandhu** [matthiasguentert/azure-naming-convention-initiative#2]
Afternoon,
i had to edit the rg- template 
from:

`"type": {
            "value": "Microsoft.Resources/resourceGroups"
          }`

to:

`{
            "field": "type",
            "equals": "microsoft.resources/subscriptions/resourcegroups"
          },`

in order for it to work.
Thanks,

**Comment by matthiasguentert** [comment]
Dear @jagsandhu, 

thanks for reporting that issue. It is fixed now (already merged to master)! 

Best regards, Matthias
